trigger: none

pool:
  name: 'DevOps Insider ka shair'

variables:
  code_location: '$(System.DefaultWorkingDirectory)/Terraform code'
  backend_svc: 'mehdiwif'

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: $(code_location)
    backendServiceArm: $(backend_svc)
    backendAzureRmResourceGroupName: 'mehdi_rg'
    backendAzureRmStorageAccountName: 'mehdihyd1996'
    backendAzureRmContainerName: 'mehdicontainer'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTask@5
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: $(code_location)
    environmentServiceNameAzureRM: '$(backend_svc)'


- task: TerraformTask@5
  displayName: 'Terraform Apply with auto approve'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '-auto-approve'
    workingDirectory: $(code_location)
    environmentServiceNameAzureRM: '$(backend_svc)'


